import Header from '@/components/header/header';
import { WebSocketProvider } from '../components/webSocketProvider/webSocketProvider';
import styles from './globals.module.css';

export const metadata = {
  title: 'Reticketfy',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={styles.body}>
        <WebSocketProvider />
        <Header />
        <div  className={styles.content}>
          {children}
        </div>
      </body>
    </html>
  );
}